version: '2'
networks:
  zk:
    driver: bridge
  elk:
    driver: bridge
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    networks:
    - default
    - zk
    ports:
    - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
    - default
    - zk
    links:
      - zookeeper
    ports:
      - 19092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
 
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    networks:
      - zk
      - default
    links:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    ports:
      - 18081:8081
 
  kafka-rest:
      image: confluentinc/cp-kafka-rest:latest
      links:
          - zookeeper
          - schema-registry
      ports:
        - 18082:8082
      environment:
        KAFKA_REST_HOST_NAME: restproxy
        KAFKA_REST_ID_CONFIG: 1
        KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - elk

  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
