version: '2'
networks:
  zk:
    driver: bridge
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    networks:
    - default
    - zk
    ports:
    - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
    - default
    - zk
    links:
      - zookeeper
    ports:
      - 19092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
 
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    networks:
      - zk
      - default
    links:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    ports:
      - 18081:8081
 
  restproxy:
      image: confluentinc/cp-kafka-rest:latest
      links:
          - zookeeper
          - schema-registry
      ports:
        - 18082:8082
      environment:
        KAFKA_REST_HOST_NAME: restproxy
        KAFKA_REST_ID_CONFIG: 1
        KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_kafka.conf:/etc/nginx/conf.d/kafka_proxy.template
    links:
      - restproxy
      - schema-registry
    environment:
      - NGINX_HOST=confluent-platform
      - NGINX_PORT=8080
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/kafka_proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
